version: "3.8"

services:

  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    environment:
      - CLUSTER_NAME=test
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
      - HDFS_CONF_dfs_namenode_rpc_address=namenode:8020

    ports:
      - "9870:9870"
      - "8020:8020"
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
      - ./namenode-entrypoint.sh:/namenode-entrypoint.sh
      - ./app/conf/yarn/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
    command: [ "bash", "/namenode-entrypoint.sh" ]

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    environment:
      - CLUSTER_NAME=test
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
    ports:
      - "9864:9864"
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    depends_on:
      - namenode

  hive-server:
    image: bde2020/hive:2.3.2-postgresql-metastore
    container_name: hive-server
    environment:
      - HIVE_METASTORE_DB_TYPE=postgres
      - HIVE_METASTORE_HOST=host.docker.internal
      - HIVE_METASTORE_DB_NAME=metastore_hive
      - HIVE_METASTORE_USER=postgres
      - HIVE_METASTORE_PASSWORD=20030205
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020

    volumes:
      - ./hive-entrypoint.sh:/hive-entrypoint.sh
      - ./app/conf/hive/hive-site.xml:/opt/hive/conf/hive-site.xml
      - ./app/conf/jars/postgresql-42.7.3.jar:/opt/hive/lib/postgresql-42.7.3.jar
    command: ["bash", "/hive-entrypoint.sh"]
    ports:
      - "10000:10000"
    depends_on:
      - namenode
      - datanode

  spark-pyspark:
    build: .
    container_name: projet_bdf3
    environment:
      - PYSPARK_PYTHON=python
      - PYSPARK_DRIVER_PYTHON=python
      - HADOOP_CONF_DIR=/opt/hadoop/conf
    ports:
      - "4040:4040"
    volumes:
      - ./app:/app
      - ./app/conf/hive/hive-site.xml:/opt/spark/conf/hive-site.xml
      - ./app/conf/jars/postgresql-42.7.3.jar:/opt/spark/jars/postgresql-42.7.3.jar
      - ./app/conf/yarn/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
      - ./app/conf/yarn/yarn-site.xml:/opt/hadoop/etc/hadoop/yarn-site.xml
      - ./app/conf/yarn/mapred-site.xml:/opt/hadoop/etc/hadoop/mapred-site.xml
    depends_on:
      - hive-server
      - namenode

  resourcemanager:
    build:
      context: .
      dockerfile: Dockerfile.resourcemanager
    container_name: resourcemanager
    environment:
      - YARN_CONF_yarn_resourcemanager_hostname=resourcemanager
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
    ports:
      - "8088:8088"
      - "8032:8032"
    depends_on:
      - namenode
    volumes:
      - ./app/conf/yarn/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
      - ./app/conf/yarn/yarn-site.xml:/opt/hadoop/etc/hadoop/yarn-site.xml
      - ./app/conf/yarn/mapred-site.xml:/opt/hadoop/etc/hadoop/mapred-site.xml

  nodemanager:
    build:
      context: .
      dockerfile: Dockerfile.nodemanager
    container_name: nodemanager
    hostname: nodemanager
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
      - YARN_CONF_yarn_resourcemanager_hostname=resourcemanager
    depends_on:
      - resourcemanager
      - namenode
    volumes:
      - ./app/conf/yarn/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
      - ./app/conf/yarn/yarn-site.xml:/opt/hadoop/etc/hadoop/yarn-site.xml
    ports:
      - "8042:8042"

volumes:
  hadoop_namenode:
  hadoop_datanode:
