version: "3.8"

services:

  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    environment:
      - CLUSTER_NAME=test
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
      - HDFS_CONF_dfs_namenode_rpc_address=namenode:8020

    ports:
      - "9870:9870"
      - "8020:8020"
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
      - ./namenode-entrypoint.sh:/namenode-entrypoint.sh
      - ./app/preprocessor/conf/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
    command: [ "bash", "/namenode-entrypoint.sh" ]

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    environment:
      - CLUSTER_NAME=test
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
    ports:
      - "9864:9864"
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    depends_on:
      - namenode

  hive-server:
    image: bde2020/hive:2.3.2-postgresql-metastore
    container_name: hive-server
    environment:
      - HIVE_METASTORE_DB_TYPE=postgres
      - HIVE_METASTORE_HOST=host.docker.internal
      - HIVE_METASTORE_DB_NAME=metastore_hive
      - HIVE_METASTORE_USER=postgres
      - HIVE_METASTORE_PASSWORD=130902
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020

    volumes:
      - ./hive-entrypoint.sh:/hive-entrypoint.sh
      - ./app/preprocessor/conf/hive-site.xml:/opt/hive/conf/hive-site.xml
      - ./app/preprocessor/conf/postgresql-42.7.3.jar:/opt/hive/lib/postgresql-42.7.3.jar
    command: ["bash", "/hive-entrypoint.sh"]
    ports:
      - "10000:10000"
    depends_on:
      - namenode
      - datanode

  spark-pyspark:
    build: .
    container_name: projet_bdf3
    environment:
      - PYSPARK_PYTHON=python
      - PYSPARK_DRIVER_PYTHON=python
    ports:
      - "4040:4040"
    volumes:
      - ./app:/app
      - ./app/preprocessor/conf/hive-site.xml:/opt/spark/conf/hive-site.xml
      - ./app/preprocessor/conf/postgresql-42.7.3.jar:/opt/spark/jars/postgresql-42.7.3.jar
    depends_on:
      - hive-server
      - namenode

volumes:
  hadoop_namenode:
  hadoop_datanode:
